project_name: gvid
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gvid
    main: ./cmd/gvid
    binary: gvid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: gvi-tui
    main: ./cmd/gvi-tui
    binary: gvi-tui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

nfpms:
  - id: packages
    package_name: gvid
    vendor: Intent Solutions
    homepage: https://github.com/intent-solutions-io/gastown-viewer-intent
    maintainer: Jeremy Longshore <jeremy@intent-solutions.io>
    description: Mission Control dashboard for Gastown multi-agent workspaces
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/local/bin
    contents:
      - src: ./deploy/gvid.service
        dst: /etc/systemd/system/gvid.service
        type: config

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: gvid
    repository:
      owner: intent-solutions-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/intent-solutions-io/gastown-viewer-intent
    description: Mission Control dashboard for Gastown multi-agent workspaces
    license: MIT
    install: |
      bin.install "gvid"
      bin.install "gvi-tui"
    test: |
      system "#{bin}/gvid", "--version"

release:
  github:
    owner: intent-solutions-io
    name: gastown-viewer-intent
  draft: false
  prerelease: auto
